### ISSUE TITLE
consider changing spec

### ISSUE THREAD

**Issue by the-widget** [learn-co-curriculum/js-spotify-api-ajax#17]
IMHO, the spec should be more liberal. On line 23, for `describe("#chartData", function(){.`, the spec should allow for chart.datasets to include `type: "bar"`. This is the standard way that is shown in the Chart.js documentation and seems most common. The method in the solution: `new Chart(ctx).Bar(data);` also works but is not shown in the documentation.

**Comment by NoneOfMaster** [comment]
I believe that this is the issue which has ensnared me in the spec as well. My chart is the same as the one in the ReadMe but spotify-chart.spec.js #chartData spec (line 23) will not pass:

![screen shot 2016-05-06 at 10 19 43 am](https://cloud.githubusercontent.com/assets/12436033/15080728/6087d00a-1374-11e6-9990-3d3bb597864f.png)

I also had to change the index script from the given Chart.js to the one from cloudflare:

![screen shot 2016-05-06 at 10 18 55 am](https://cloud.githubusercontent.com/assets/12436033/15080752/77e0790a-1374-11e6-98f7-bf6d398cf2bc.png)

Also it's unclear that this is to take place in Sweden:

![screen shot 2016-05-06 at 10 24 03 am](https://cloud.githubusercontent.com/assets/12436033/15080820/b59e2e72-1374-11e6-88cf-7b472c226a97.png)
