### ISSUE TITLE
Regarding the spec test for extractTop10Tracks()

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/js-spotify-api-ajax#20]
https://github.com/learn-co-curriculum/js-spotify-api-ajax/blob/master/spec/spotify-chart.spec.js#L7

I believe the `spotifyData.tracks` parameter passed into the `extractTop10Tracks` expectation here...

```
describe("#extractTop10Tracks", function() {
  it("returns the first 10 tracks from the tracks array", function(){
    expect(extractTop10Tracks(spotifyData.tracks).length).toEqual(10);
  });
});
```

...should be plain, old `spotifyData`. Isn't the whole purpose of the `extractTop10Tracks()` function to return an array of tracks culled from the JSON object retrieved from Spotify?

**Comment by gj** [comment]
cc: @cernanb

**Comment by gj** [comment]
Later noted here: https://github.com/learn-co-curriculum/js-spotify-api-ajax/issues/25

**Comment by drakeltheryuujin** [comment]
@gj Thank you for your feedback! That test has been modified. 💙
