### ISSUE TITLE
JSONP not supported by Spotify API.

### ISSUE THREAD

**Issue by thekayness** [learn-co-curriculum/js-spotify-api-ajax#21]
Specs specify to use jsonp, not available via Spotify

**Comment by Lukeghenco** [comment]
Thank @thekayness

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/js-spotify-api-ajax/commit/d457f691afe0f2711d25571f03561e9d9bf0b8d0. Thanks @thekayness !
