### ISSUE TITLE
extract top tracks

### ISSUE THREAD

**Issue by ckrausko** [learn-co-curriculum/js-spotify-api-ajax#25]
The function extractTop10Tracks() is entirely pointless to have in this lab. Spotify's API will only return the top 10 tracks 

"On success, the HTTP status code in the response header is 200 OK and the response body contains an object whose key is "tracks" and whose value is an array of up to 10 track objects in JSON format."

If you're wanting to test the ability to slice the returned array then perhaps rewrite the format to only display the top 5 tracks or something less than the default return value.

**Comment by achasveachas** [comment]
Came to add this issue as well.

**Comment by drakeltheryuujin** [comment]
@ckrausko Thank you for your feedback! That test has been modified. 💙
