### ISSUE TITLE
Data structure of SpotifyAPI has changed

### ISSUE THREAD

**Issue by eaud** [learn-co-curriculum/js-spotify-api-ajax#8]
causing Test 1 of this spec to fail when implementing for IRL success

**Comment by cbdileo** [comment]
I ran the tests and all passed. Was there a specific error you saw?

**Comment by vicfriedman** [comment]
the spotify API has actually changed their endpoints and is not longer the supporting the URL specified in the Readme. The tests are using fixtures so they're just stubbing an API request.

We can either have the actual lab (in browser function) work with a stub as well and make that clear to the student that if they tried to curl the request it's a no go or we can change the endpoint  to graph a different data set.

**Comment by cbdileo** [comment]
Ah I see, I was confused because the solutions branch seemed to work fine. I will check again.

**Comment by AnnJohn** [comment]
hi @cbdileo could you take a look at this again if you haven't yet/ Thanks

**Comment by cbdileo** [comment]
@AnnJohn I did and I changed it to use the a different but similar Spotify API endpoint

**Comment by AnnJohn** [comment]
thanks @cbdileo. @vicfriedman can you take a final look?

**Comment by cbdileo** [comment]
There are two new pull requests that address this issue. PR #12, PR #11

**Comment by cbdileo** [comment]
@vicfriedman PR's were merged can we close this issue now?

**Comment by AnnJohn** [comment]
closing, thanks
